
datasources:
    - name: local
      user: videoMail
      password: videoMail2023!
      host: localhost
      port: 3306
      db: videoMail

constants:
      path_qrcode: "qrCode/"
      domain: "www.vmail.com/"


